### ISSUE TITLE
Installing CMake or Other Dependencies

### ISSUE THREAD

**Issue by reedacartwright** [r-windows/rtools-packages#107]
I understand that I can install CMake via pacman in the rtools bash interface.  However, is there a recommended way to run pacman on windows from withing R 4.0 or via the installation script of my package?

Is putting a pacman command in configure.win recommended? (I suspect that it should be avoided.)

**Comment by jeroen** [comment]
Indeed, I recommend you do not call cmake from R packages. In fact I recommend you don't use a configure.win script at all because it is never really needed. You can just special case the windows make configuration in `src/Makevars.win`. 

You should only use cmake to build your external libraries in `rtools-packages` and link those from R so you special build tools are needed for building the R package.

**Comment by reedacartwright** [comment]
My plan is to eventually submit my package to cran for binary packaging on
Windows, and I'm trying to prepare for that.

The external library doesn't have a large open source userbase, so it will
need to be provided as a part of the R package, and be able to be compiled
by install.packages().

So I have two questions.

1) Can I use CMake on the CRAN's Windows package building servers?

2) Can I get CMake to run on, say, Linux when installing from source?


If it helps, this is the library I'm trying to update for R/Rtools 4.0.

**Comment by jeroen** [comment]
You mean leveldb?

**Comment by reedacartwright** [comment]
Yeah, except it is a fork produced by Microsoft/Mojang specifically for Minecraft that has a different ABI thank the standard one.

**Comment by jeroen** [comment]
So it won't work with libleveldb-dev from Debian? https://packages.debian.org/sid/libleveldb-dev

**Comment by reedacartwright** [comment]
Nope.

**Comment by jeroen** [comment]
That might be tricky. Does it depend on other c/c++ libraries?

Generally it's very difficult to properly build complex embedded libraries on the fly during R package installation. I always avoid this in my packages because it is very hard to get right to work on all the different operating system.

I don't know what tools are available on the cran build servers, if they have cmake, and which version. It may be different for each platform and each server. Maybe you can run cmake locally and just ship the `Makefile` that cmake produces?

**Comment by reedacartwright** [comment]
Only zlib.

I have considered shipping the Makefiles or Precompiled libraries for windows if there is no other solution.

Ideally, I wish there was a way for a package to tell R that it depends on CMake and R could provide it via RTools or on the build server.

**Comment by jeroen** [comment]
I think there is a cmake installed on the winbuilder because some other cran packages also seem to depend on it. But I don't know anything about this myself.

But you can easily test it by uploading your package to winbuilder: https://win-builder.r-project.org/

**Comment by reedacartwright** [comment]
I'll test it out again, once I get the package working with Rtools 4.0.

**Comment by reedacartwright** [comment]
I decided to use a hard coded makefile for mingw. Thanks for the help.
