### ISSUE TITLE
make: c:/Rtools/mingw_64/bin/dlltool: Command not found

### ISSUE THREAD

**Issue by pat-s** [r-windows/rtools-packages#41]
When trying to compile with Rtools on x64 arch on Windows (appveyor): https://ci.appveyor.com/project/ropensci/tic-vp4mj/builds/27650481#L528

I am currently bypassing source installations by using binaries only but would like to get this working.

**Comment by jeroen** [comment]
This is the wrong repository to report this. Your problem has nothing to do with the new toolchain.

I think your problem is that your package does not include C code, and therefore the compiler does not get installed. However it tries to install the `curl` package from source because it was recently updated and the binary is not yet available.

You can force the installation of rtools on appveyor by setting this in your `appveyor.yml` file:

```
environment:
  global:
    USE_RTOOLS: true
```

Or you can wait a few days. The problem will automatically solve itself once the new binary packages for `curl` are on CRAN.

**Comment by pat-s** [comment]
Ahh :man_facepalming: 
Sorry, I thought `USE_RTOOLS: true` was set in this build. My bad.

> Or you can wait a few days. The problem will automatically solve itself once the new binary packages for curl are on CRAN.

Thanks, I am aware of binary/src problems. Currently trying to get appveyor somewhat more "stable" by using binaries only but also having a working "src setup". 

Sorry for picking the wrong repo, I was in a hurry a bit - thanks for the detailed response!!
